In [109]:
#import Libraries
import requests
import pandas as pd
import time

In [110]:
df=pd.DataFrame(columns=['movie_id','movie_title','overview','release_date','original_language','popularity','vote_average','vote_count'])

In [111]:
def get_movies(df):
    for i in range(1,429):
        response = requests.get("https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}".format(i)).json()
        for movie in response['results']:

            movie_id=movie['id']
            movie_title=movie['title']
            overview=movie['overview']
            release_date=movie['release_date']
            original_language=movie['original_language']
            popularity=movie['popularity']
            vote_average=movie['vote_average']
            vote_count=movie['vote_count']

            df=df.append({'movie_id':movie_id,"movie_title":movie_title,"overview":overview,"release_date":release_date,"original_language":original_language,"popularity":popularity,"vote_average":vote_average,"vote_count":vote_count},ignore_index=True)
    return df

In [112]:
df=get_movies(df)

In [113]:
df

,movie_id,movie_title,overview,release_date,original_language,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,en,121.863,8.711,25404
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,en,111.254,8.708,19346
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,en,64.010,8.592,11668
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,en,71.623,8.572,15037
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,en,52.495,8.545,7969
...,...,...,...,...,...,...,...,...
8555,12657,Soul Plane,Following a ridiculously awful flight that lea...,2004-05-28,en,20.640,5.401,400
8556,338964,Bad Santa 2,"Fueled by cheap whiskey, greed and hatred, Wil...",2016-11-23,en,31.472,5.400,733
8557,82990,Paranormal Activity 4,It has been five years since the disappearance...,2012-10-17,en,23.478,5.400,1779
8558,43593,Piranha 3D,Each year the population of sleepy Lake Victor...,2010-08-20,en,52.987,5.400,2059
8559,1641,Forces of Nature,"Ben Holmes, a professional book-jacket blurbol...",1999-03-12,en,10.601,5.400,494

In [114]:
df.to_csv('Top_rated_movie.csv')